# home-manager module: the session half of hyprpower.
#
# Owns the two things that must run as the user: the executable and the
# hypridle unit that calls back into it. The system half (logind, charge
# thresholds, ACPI events) is nix/nixos.nix.
#
# It does NOT own the profile. hyprpower reads
# $XDG_CONFIG_HOME/hyprpower/profile.toml, and anything home-manager
# generates is a read-only store symlink the TUI could never write -- which
# is why this seeds or links, and never generates.
{ config, lib, pkgs, ... }:

let
  cfg = config.programs.hyprpower;
  exe = "${config.home.homeDirectory}/.local/bin/hyprpower";
in
{
  options.programs.hyprpower = {
    enable = lib.mkEnableOption "the hyprpower idle and power policy";

    checkout = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = "/home/you/projects/hyprpower";
      description = ''
        Absolute path to a working checkout. When set, the wrapper runs the
        tool from there so editing the source takes effect without a rebuild.
        Leave null to run the packaged build instead.
      '';
    };

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.callPackage ./package.nix { };
      description = "Used when `checkout` is null.";
    };

    profileSource = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = "/etc/nixos/hyprpower/profile.toml";
      description = ''
        Absolute path to a profile you keep under version control. When set,
        ~/.config/hyprpower/profile.toml becomes a symlink to it and the TUI
        writes through, so edits land in your repo and a fresh machine
        rebuilds with your policy rather than the shipped default.

        mkOutOfStoreSymlink, not home.file: home.file would copy it into the
        store and the result would be read-only.

        This is a convenience, not a requirement -- `ln -s` does the same
        thing, which is why hyprpower only ever knows the one XDG path.
      '';
    };

    seedProfile = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Copy the shipped default to ~/.config/hyprpower/profile.toml when no
        profile exists yet. Ignored when profileSource is set. A copy, not a link: the TUI writes to this file,
        so home-manager cannot generate it -- anything it generates is a
        read-only /nix/store symlink.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # A wrapper rather than plain `package` on PATH, for two reasons that both
    # cost real debugging:
    #
    #   * hypridle runs as a user service with a minimal environment. A bare
    #     `brightnessctl` is not found there, and neither is
    #     `#!/usr/bin/env bash` -- which exits 127 and silently kills every
    #     rung. Hence the explicit PATH and the absolute shebang.
    #   * tomlkit must be present or the first policy edit fails, since edits
    #     rewrite policy.toml without destroying its comments.
    home.file.".local/bin/hyprpower" = {
      executable = true;
      text =
        let py = pkgs.python3.withPackages (ps: [ ps.textual ps.tomlkit ]);
            path = lib.makeBinPath [ pkgs.brightnessctl pkgs.systemd pkgs.hyprland ];
        in ''
          #!${pkgs.bash}/bin/bash
          export PATH="${path}:$PATH"
        '' + (if cfg.checkout != null then ''
          exec ${py}/bin/python3 -c \
            'import sys; sys.path.insert(0, "${cfg.checkout}"); from hyprpower.cli import main; main()' "$@"
        '' else ''
          exec ${lib.getExe cfg.package} "$@"
        '');
    };

    xdg.configFile."hyprpower/profile.toml" = lib.mkIf (cfg.profileSource != null) {
      source = config.lib.file.mkOutOfStoreSymlink cfg.profileSource;
    };

    home.activation.hyprpowerProfile =
      lib.mkIf (cfg.seedProfile && cfg.profileSource == null)
      (lib.hm.dag.entryAfter [ "writeBoundary" ] ''
        p="''${XDG_CONFIG_HOME:-$HOME/.config}/hyprpower/profile.toml"
        if [ ! -e "$p" ]; then
          run mkdir -p "$(dirname "$p")"
          run cp ${../hyprpower/default.toml} "$p"
          run chmod u+w "$p"
        fi
      '');

    # Replaces services.hypridle.enable, whose unit cannot take -c. If you
    # also enable programs.hyprlock, set services.hypridle.enable to
    # lib.mkForce false -- hyprlock turns hypridle on as a side effect.
    systemd.user.services.hypridle = {
      Unit = {
        Description = "Hyprland idle daemon (config generated by hyprpower)";
        PartOf = [ "graphical-session.target" ];
        After = [ "graphical-session.target" ];
        ConditionEnvironment = "WAYLAND_DISPLAY";
      };
      Service = {
        Type = "simple";
        # Regenerate on every start so a boot lands on the declared policy
        # even if nothing has run `hyprpower apply` since policy.toml changed.
        ExecStartPre = "${exe} apply --no-restart";
        ExecStart = "${pkgs.hypridle}/bin/hypridle -c %h/.local/state/hyprpower/hypridle.conf";
        Restart = "on-failure";
      };
      Install.WantedBy = [ "graphical-session.target" ];
    };
  };
}
