# home-manager module: the session half of hyprpower.
#
# Owns the three things that must run as the user -- the policy file, the
# executable, and the hypridle unit that calls back into it. The system half
# (logind, charge thresholds, ACPI events) is nix/nixos.nix.
{ config, lib, pkgs, ... }:

let
  cfg = config.programs.hyprpower;
  exe = "${config.home.homeDirectory}/.local/bin/hyprpower";
in
{
  options.programs.hyprpower = {
    enable = lib.mkEnableOption "the hyprpower idle and power policy";

    policyFile = lib.mkOption {
      type = lib.types.str;
      example = "/home/you/projects/hyprpower/config/policy.toml";
      description = ''
        Absolute path to your policy.toml. It is symlinked into
        ~/.config/hyprpower/ with mkOutOfStoreSymlink, NOT home.file:
        home.file would make it a read-only /nix/store symlink and the TUI
        could never write to it.
      '';
    };

    checkout = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = "/home/you/projects/hyprpower";
      description = ''
        Absolute path to a working checkout. When set, the wrapper runs the
        tool from there so editing the source takes effect without a rebuild.
        Leave null to run the packaged build instead.
      '';
    };

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.callPackage ./package.nix { };
      description = "Used when `checkout` is null.";
    };
  };

  config = lib.mkIf cfg.enable {
    xdg.configFile."hyprpower/policy.toml".source =
      config.lib.file.mkOutOfStoreSymlink cfg.policyFile;

    # A wrapper rather than plain `package` on PATH, for two reasons that both
    # cost real debugging:
    #
    #   * hypridle runs as a user service with a minimal environment. A bare
    #     `brightnessctl` is not found there, and neither is
    #     `#!/usr/bin/env bash` -- which exits 127 and silently kills every
    #     rung. Hence the explicit PATH and the absolute shebang.
    #   * tomlkit must be present or the first policy edit fails, since edits
    #     rewrite policy.toml without destroying its comments.
    home.file.".local/bin/hyprpower" = {
      executable = true;
      text =
        let py = pkgs.python3.withPackages (ps: [ ps.textual ps.tomlkit ]);
            path = lib.makeBinPath [ pkgs.brightnessctl pkgs.systemd pkgs.hyprland ];
        in ''
          #!${pkgs.bash}/bin/bash
          export PATH="${path}:$PATH"
        '' + (if cfg.checkout != null then ''
          exec ${py}/bin/python3 -c \
            'import sys; sys.path.insert(0, "${cfg.checkout}"); from hyprpower.cli import main; main()' "$@"
        '' else ''
          exec ${lib.getExe cfg.package} "$@"
        '');
    };

    # Replaces services.hypridle.enable, whose unit cannot take -c. If you
    # also enable programs.hyprlock, set services.hypridle.enable to
    # lib.mkForce false -- hyprlock turns hypridle on as a side effect.
    systemd.user.services.hypridle = {
      Unit = {
        Description = "Hyprland idle daemon (config generated by hyprpower)";
        PartOf = [ "graphical-session.target" ];
        After = [ "graphical-session.target" ];
        ConditionEnvironment = "WAYLAND_DISPLAY";
      };
      Service = {
        Type = "simple";
        # Regenerate on every start so a boot lands on the declared policy
        # even if nothing has run `hyprpower apply` since policy.toml changed.
        ExecStartPre = "${exe} apply --no-restart";
        ExecStart = "${pkgs.hypridle}/bin/hypridle -c %h/.local/state/hyprpower/hypridle.conf";
        Restart = "on-failure";
      };
      Install.WantedBy = [ "graphical-session.target" ];
    };
  };
}
