"""Render the policy into what the daemons read, and reload them."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

from . import policy

def state_dir() -> Path:
    d = Path(os.environ.get("XDG_STATE_HOME") or os.path.expanduser("~/.local/state"))
    d = d / "thinkpower"
    d.mkdir(parents=True, exist_ok=True)
    return d


def which(name: str) -> str:
    out = subprocess.run(["which", name], capture_output=True, text=True)
    return out.stdout.strip() or name


def thinkpower_exe() -> str:
    """Absolute path, always.

    hypridle runs with a minimal PATH, so a bare name in the generated config
    fails with exit 127 and every rung silently stops working. Never return
    something unqualified.
    """
    for candidate in (os.environ.get("THINKPOWER_EXE"),
                      os.path.expanduser("~/.local/bin/thinkpower"),
                      which("thinkpower")):
        if candidate and candidate.startswith("/") and os.path.exists(candidate):
            return candidate
    raise SystemExit("cannot locate an absolute path to thinkpower; "
                     "set THINKPOWER_EXE")


def apply_session(restart: bool = True) -> Path:
    """Write the hypridle config and point hypridle at it.

    The unit itself is declared in home.nix with -c pointing here, so this
    only has to write the file and restart. (It used to install a systemd
    drop-in too; that became redundant once the unit was declarative, and
    left imperative state shadowing it.)
    """
    conf = state_dir() / "hypridle.conf"
    exe = thinkpower_exe()
    conf.write_text(policy.render_hypridle(policy.load(), exe=exe))

    if restart:
        subprocess.run(["systemctl", "--user", "restart", "hypridle.service"], check=False)
    return conf


LOGIND_DROPIN = """# GENERATED by thinkpower from policy.toml — do not edit.
# Drop-ins override the main logind.conf, so this wins over whatever NixOS
# generated. HandlePowerKey is 'ignore' because logind has no power-source
# variant for keys; acpid routes the press to `thinkpower event power`, which
# reads [button.power] and can differ by AC/battery.
[Login]
HandleLidSwitchExternalPower={lid_ac}
HandleLidSwitch={lid_battery}
HandleLidSwitchDocked={lid_docked}
HandlePowerKey=ignore
"""

LOGIND_PATH = Path("/etc/systemd/logind.conf.d/50-thinkpower.conf")


def apply_system(reload: bool = True) -> Path:
    """Write the logind drop-in. Needs root."""
    pol = policy.load()
    LOGIND_PATH.parent.mkdir(parents=True, exist_ok=True)
    LOGIND_PATH.write_text(LOGIND_DROPIN.format(
        lid_ac=pol["lid"]["ac"], lid_battery=pol["lid"]["battery"],
        lid_docked=pol["lid"]["docked"]))
    if reload:
        subprocess.run(["systemctl", "reload", "systemd-logind"], check=False)

    # Charge thresholds. TLP used to own these; it still reasserts its own
    # values on service restart, so it must no longer set them in tlp.conf.
    import glob
    bat = sorted(glob.glob("/sys/class/power_supply/BAT*"))[0]
    for key, attr in (("start", "charge_control_start_threshold"),
                      ("stop", "charge_control_end_threshold")):
        Path(f"{bat}/{attr}").write_text(str(pol["battery"]["charge"][key]))
    return LOGIND_PATH
