"""Render the policy into what the daemons read, and reload them."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

from . import policy

def state_dir() -> Path:
    d = Path(os.environ.get("XDG_STATE_HOME") or os.path.expanduser("~/.local/state"))
    d = d / "hyprpower"
    d.mkdir(parents=True, exist_ok=True)
    return d


def which(name: str) -> str:
    out = subprocess.run(["which", name], capture_output=True, text=True)
    return out.stdout.strip() or name


def hyprpower_exe() -> str:
    """Absolute path, always.

    hypridle runs with a minimal PATH, so a bare name in the generated config
    fails with exit 127 and every rung silently stops working. Never return
    something unqualified.
    """
    for candidate in (os.environ.get("HYPRPOWER_EXE"),
                      os.path.expanduser("~/.local/bin/hyprpower"),
                      which("hyprpower")):
        if candidate and candidate.startswith("/") and os.path.exists(candidate):
            return candidate
    raise SystemExit("cannot locate an absolute path to hyprpower; "
                     "set HYPRPOWER_EXE")


def apply_session(restart: bool = True) -> Path:
    """Write the hypridle config and point hypridle at it.

    The unit itself is declared in home.nix with -c pointing here, so this
    only has to write the file and restart. (It used to install a systemd
    drop-in too; that became redundant once the unit was declarative, and
    left imperative state shadowing it.)
    """
    conf = state_dir() / "hypridle.conf"
    exe = hyprpower_exe()
    conf.write_text(policy.render_hypridle(policy.load(), exe=exe))

    if restart:
        subprocess.run(["systemctl", "--user", "restart", "hypridle.service"], check=True)
    return conf


LOGIND_DROPIN = """# GENERATED by hyprpower from policy.toml — do not edit.
# Drop-ins override the main logind.conf, so this wins over whatever NixOS
# generated. HandlePowerKey is 'ignore' because logind has no power-source
# variant for keys; acpid routes the press to `hyprpower event power`, which
# reads [button.power] and can differ by AC/battery.
[Login]
HandleLidSwitchExternalPower={lid_ac}
HandleLidSwitch={lid_battery}
HandleLidSwitchDocked={lid_docked}
HandlePowerKey=ignore
"""

LOGIND_PATH = Path("/etc/systemd/logind.conf.d/50-hyprpower.conf")
SLEEP_PATH = Path("/etc/systemd/sleep.conf.d/50-hyprpower.conf")

SLEEP_DROPIN = """# GENERATED by hyprpower from policy.toml — do not edit.
# The gap between [idle.suspend] and [idle.hibernate].
[Sleep]
HibernateDelaySec={delay}
"""


def sleep_text(pol: dict) -> str | None:
    """None when there is nothing to write, INCLUDING an unresolvable
    conflict. It must not raise: verify and the flags both call this, and
    throwing here took down the very screen you would fix the conflict on."""
    delay = policy.hibernate_delay(pol)
    return None if delay is None else SLEEP_DROPIN.format(delay=delay)


def logind_want(pol: dict) -> dict[str, str]:
    """logind property -> the value we intend, in systemd's vocabulary.

    Shared with verify so the comparison and the write cannot disagree: the
    lid is written translated, so it must be checked translated.
    """
    return {
        "HandleLidSwitchExternalPower": policy.systemd_sleep(pol, "ac", pol["lid"]["ac"]),
        "HandleLidSwitch": policy.systemd_sleep(pol, "battery", pol["lid"]["battery"]),
        # docked is orthogonal to the power source, so no escalation applies.
        "HandleLidSwitchDocked": policy.SYSTEMD.get(pol["lid"]["docked"],
                                                    pol["lid"]["docked"]),
    }


def apply_system(reload: bool = True) -> Path:
    """Write the logind drop-in and the charge thresholds. Requires root."""
    if os.geteuid() != 0:
        raise SystemExit("hyprpower apply --system must run as root "
                         "(writes /etc/systemd/logind.conf.d and battery sysfs)")
    pol = policy.load()
    LOGIND_PATH.parent.mkdir(parents=True, exist_ok=True)
    want = logind_want(pol)
    LOGIND_PATH.write_text(LOGIND_DROPIN.format(
        lid_ac=want["HandleLidSwitchExternalPower"],
        lid_battery=want["HandleLidSwitch"],
        lid_docked=want["HandleLidSwitchDocked"]))
    if reload:
        subprocess.run(["systemctl", "reload", "systemd-logind"], check=True)

    if len(gaps := policy.delay_gaps(pol)) > 1:
        raise SystemExit(
            f"suspend->hibernate gaps differ by power source ({sorted(gaps)}s) "
            f"but HibernateDelaySec is one global value. Make the gaps equal, "
            f"or use hibernate on only one source.")
    want = sleep_text(pol)
    if want is None:
        SLEEP_PATH.unlink(missing_ok=True)
    else:
        SLEEP_PATH.parent.mkdir(parents=True, exist_ok=True)
        SLEEP_PATH.write_text(want)

    # Charge thresholds. TLP used to own these; it still reasserts its own
    # values on service restart, so it must no longer set them in tlp.conf.
    import glob
    bat = sorted(glob.glob("/sys/class/power_supply/BAT*"))[0]
    start = Path(f"{bat}/charge_control_start_threshold")
    Path(f"{bat}/charge_control_end_threshold").write_text(
        str(pol["battery"]["charge"]["stop"]))
    start.write_text(str(pol["battery"]["charge"]["start"]))
    # Nudge the EC. Observed 2026-09-27: after a correct write it sat at
    # "Not charging" for >12s at 72% with a 75% start threshold; rewriting
    # the same value started charging immediately. Without this a correctly
    # applied policy looks like it did nothing.
    start.write_text(str(pol["battery"]["charge"]["start"]))
    return LOGIND_PATH
