"""Load policy.toml and render what the daemons read.

The policy is the source of truth; this turns it into a hypridle config.
hypridle becomes a timer and hyprpower is the policy engine: every listener
calls back into `hyprpower on <source>` to decide whether it applies, and
`hyprpower do <action>` to act.
"""

from __future__ import annotations

import os
import re
import tomllib
from pathlib import Path

SOURCES = ("ac", "battery")

# Display steps restore on activity; lock and suspend do not.
STEPS = [("dim", "dim", True),
         ("backlight_off", "backlight-off", True),
         ("display_off", "display-off", True),
         ("lock", "lock", False),
         ("suspend", "suspend", False),
         ("hibernate", "hibernate", False)]

# Which row an emitted action belongs to. suspend-then-hibernate is the
# composition of two rungs and is attributed to the one that triggers it.
ROW = {"dim": "idle.dim", "backlight-off": "idle.backlight_off",
       "display-off": "idle.display_off", "lock": "idle.lock",
       "suspend": "idle.suspend", "hibernate": "idle.hibernate",
       "suspend-then-hibernate": "idle.suspend"}

# Emitted action -> does the machine survive the battery running out in it.
SLEEP = {"suspend": False, "hibernate": True, "suspend-then-hibernate": True}

# Copied verbatim from the hand-written config. This carries the
# fingerprint-reader resume logic: after_sleep_cmd's try-restart exists
# because hyprlock gets exactly ONE fprintd re-claim attempt across suspend,
# and a stale instance fails it silently. Do not "simplify" this block.
GENERAL = '''general {
    lock_cmd = systemctl --user start hyprlock.service
    before_sleep_cmd = /run/current-system/sw/bin/loginctl lock-session
    after_sleep_cmd = /run/current-system/sw/bin/hyprctl dispatch dpms on; /run/current-system/sw/bin/systemctl --user try-restart hyprlock.service
}
'''


def path() -> Path:
    if env := os.environ.get("HYPRPOWER_POLICY"):
        return Path(env)
    base = os.environ.get("XDG_CONFIG_HOME") or os.path.expanduser("~/.config")
    return Path(base) / "hyprpower" / "policy.toml"


def load(p: Path | None = None) -> dict:
    return tomllib.loads((p or path()).read_text())


def seconds(v) -> int | None:
    """'2m30s' -> 150.  false -> None (never)."""
    if v is False or v is None:
        return None
    if isinstance(v, int):
        return v
    total = 0
    for n, unit in re.findall(r"(\d+)\s*([hms])", v):
        total += int(n) * {"h": 3600, "m": 60, "s": 1}[unit]
    if not total:
        raise ValueError(f"unparseable duration: {v!r}")
    return total


def rungs(pol: dict) -> list[tuple[int, str, str, bool]]:
    """The listeners to emit, as (seconds, source, action, restores).

    suspend and hibernate on the same source collapse into one
    suspend-then-hibernate listener: nothing in userspace runs while asleep,
    so a second listener could never fire. systemd does the escalation.
    """
    out = []
    for source in SOURCES:
        at = {key: seconds(pol["idle"][key][source]) for key, _a, _r in STEPS}
        fold = (at["suspend"] is not None and at["hibernate"] is not None
                and at["hibernate"] > at["suspend"])
        for key, action, restores in STEPS:
            if at[key] is None or (fold and key == "hibernate"):
                continue
            out.append((at[key], source,
                        "suspend-then-hibernate" if fold and key == "suspend"
                        else action, restores))
    return sorted(out)


def hibernate_delay(pol: dict) -> int | None:
    """Seconds to stay suspended before hibernating, or None."""
    gaps = {seconds(pol["idle"]["hibernate"][s]) - seconds(pol["idle"]["suspend"][s])
            for s in SOURCES
            if seconds(pol["idle"]["suspend"][s]) is not None
            and seconds(pol["idle"]["hibernate"][s]) is not None
            and seconds(pol["idle"]["hibernate"][s]) > seconds(pol["idle"]["suspend"][s])}
    assert len(gaps) <= 1, f"HibernateDelaySec is one global value, got {gaps}"
    return gaps.pop() if gaps else None


def render_hypridle(pol: dict, exe: str = "hyprpower") -> str:
    """One listener per step per power source, gated on the source.

    condition_cmd runs at timeout and defers on non-zero; condition_retry
    re-checks while still idle, so unplugging mid-idle lands on the battery
    rung without any extra daemon watching for the transition.
    """
    out = [
        "# GENERATED by hyprpower from policy.toml — do not edit.",
        "# Edit the policy and run `hyprpower apply`.",
        "",
        GENERAL,
    ]
    for after, source, action, restores in rungs(pol):
        lines = ["listener {",
                 f"    timeout = {after}",
                 f"    condition_cmd = {exe} on {source}",
                 f"    condition_retry = 30",
                 f"    on-timeout = {exe} do {action}"]
        if restores:
            lines.append(f"    on-resume = {exe} do restore")
        out.append("\n".join(lines) + "\n}\n")
    return "\n".join(out)


def collisions(pol: dict) -> list[tuple[int, str, list[str]]]:
    """Steps that fire at the same moment on the same power source.

    Not an error and not something to work around: both actions run and the
    end state is the same either way. But hypridle decides the order, so it
    is undefined, and undefined is worth saying out loud.
    """
    seen: dict[tuple[int, str], list[str]] = {}
    for after, source, action, _ in rungs(pol):
        seen.setdefault((after, source), []).append(action)
    return [(after, source, acts) for (after, source), acts in sorted(seen.items())
            if len(acts) > 1]


def parse_generated(text: str) -> dict[tuple[str, str], int]:
    """Read back a config WE generated: (source, action) -> seconds.

    Safe to parse because we author the format. This is deliberately not a
    general hypridle parser -- an earlier version tried that and broke the
    moment the commands changed.
    """
    out = {}
    for block in re.findall(r"listener\s*\{(.*?)\}", text, re.S):
        m_t = re.search(r"timeout\s*=\s*(\d+)", block)
        m_a = re.search(r"on-timeout\s*=.*?\bdo\s+([\w-]+)", block)
        m_s = re.search(r"condition_cmd\s*=.*?\bon\s+(ac|battery)\b", block)
        assert m_t and m_a and m_s, block
        out[(m_s.group(1), m_a.group(1))] = int(m_t.group(1))
    return out
